services:
  floods:
    build: .
    env_file: .env
    volumes:
      - ./output:/app/output
    entrypoint: ["python", "query_floods.py"]
    # docker compose run --rm floods --start 2024-09-01 --end 2024-09-30

  nyc311:
    build: .
    env_file: .env
    volumes:
      - ./output:/app/output
    entrypoint: ["python", "query_311.py"]
    # docker compose run --rm nyc311 --start 2024-09-01 --end 2024-09-30

  pipeline:
    build: .
    env_file: .env
    volumes:
      - ./output:/app/output
    entrypoint: ["python", "pipeline.py"]
    # docker compose run --rm pipeline --start 2024-09-01 --end 2024-09-30

  dashboard:
    build: .
    env_file: .env
    ports:
      - "8501:8501"
    volumes:
      - ./output:/app/output
    entrypoint: ["streamlit", "run", "dashboard.py",
                 "--server.port=8501", "--server.address=0.0.0.0",
                 "--server.headless=true"]
